spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username : postgres
    password : Tulbaga@11
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties :
      hibernate :
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: 1ade5e8fdf885851789224203544c323f68b89979f99c88fb4d573c50b92c1d7
      expiration: 86400000 # 1 udur
      refresh:
        expiration: 604800000
